# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d9017e6b6bbb4683b10ac25b8d7d3762a673507f7aa2a3e15f4749fc9c7759150679f3f6ec00467639526dfcc9a60c6cb71715ea12175fa2c0337f016b51fb4

test:
  secret_key_base: 8161bff72de4a70db84122c053e228f39b4c80559ab9963ea6c9fcf7b89187bf549efd2c44cc4365fa178307fc2500d7a90ea717ab71d1d70b1af7e1da2431c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
